env:
  browser: true
  es2021: true
extends: 
  - 'eslint:recommended'
  - 'airbnb-base'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
  max-len:  ["error", { "code": 130 }]